export enum authorizationTypes {
    FETCH_AUTHORIZATION_REQUEST = 'FETCH_AUTHORIZATION_REQUEST',
    SET_AUTHORIZATION = 'SET_AUTHORIZATION',
    ERROR_AUTHORIZATION = 'ERROR_AUTHORIZATION',
    DROP_AUTHORIZATION = 'DROP_AUTHORIZATION',
    FETCH_REGISTER = 'FETCH_REGISTER',
    SET_REGISTER = 'SET_REGISTER',
}
