export enum articleTypes {
    FETCH_ARTICLES_LIST = 'FETCH_ARTICLES_LIST_articleTypes',
    SET_ARTICLES_LIST = 'SET_ARTICLES_LIST_articleTypes',

    FETCH_ARTICLE_BY_ID = 'FETCH_ARTICLE_BY_ID_articleTypes',
    SET_ARTICLE_BY_ID = 'SET_ARTICLE_BY_ID_articleTypes',

    FETCH_DELETE_ARTICLE_BY_ID = 'FETCH_DELETE_ARTICLE_BY_ID_articleTypes',
    SET_DELETE_ARTICLE_BY_ID = 'SET_DELETE_ARTICLE_BY_ID_articleTypes',

    FETCH_CREATE_ARTICLE = 'FETCH_CREATE_ARTICLE_articleTypes',
    SET_CREATE_ARTICLE = 'SET_CREATE_ARTICLE_articleTypes',

    FETCH_EDIT_ARTICLE_BY_ID = 'FETCH_EDIT_ARTICLE_BY_ID_articleTypes',
    SET_EDIT_ARTICLE_BY_ID = 'SET_EDIT_ARTICLE_BY_ID_articleTypes',

    FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST_articleTypes',
    SET_CATEGORY_LIST = 'SET_CATEGORY_LIST_articleTypes',

    FETCH_SOURCE_LIST = 'FETCH_SOURCE_LIST_articleTypes',
    SET_SOURCE_LIST = 'SET_SOURCE_LIST_articleTypes',

    FETCH_UPLOAD_TO_MEDIUM = 'FETCH_UPLOAD_TO_MEDIUM_articleTypes',
    FETCH_UPLOAD_TO_GHOST = 'FETCH_UPLOAD_TO_GHOST_articleTypes',

    DROP_ARTICLES = 'DROP_ARTICLES_articleTypes',
}
